// Import the functions you need from the SDKs you need
import { initializeApp } from "firebase/app";
import { getFirestore, collection, getDocs, addDoc } from "firebase/firestore";
// TODO: Add SDKs for Firebase products that you want to use
// https://firebase.google.com/docs/web/setup#available-libraries

// Your web app's Firebase configuration
// For Firebase JS SDK v7.20.0 and later, measurementId is optional
const firebaseConfig = {
  apiKey: "AIzaSyAMo-e7iboSEgMHSFlzxq4vs7ZsMmIXkPQ",
  authDomain: "shopseekerrafaelmartinez.firebaseapp.com",
  projectId: "shopseekerrafaelmartinez",
  storageBucket: "shopseekerrafaelmartinez.appspot.com",
  messagingSenderId: "873380067755",
  appId: "1:873380067755:web:f9632b8be85993cbf1faee",
  measurementId: "G-QVVWYSM8T5",
};

// Initialize Firebase
const app = initializeApp(firebaseConfig);
//arranca Firestore
const DB = getFirestore(app);
//obtenemos lista de disenos
export default async function getDesigns() {
  //ref coleccion
  const collectionDesignsRef = collection(DB, "designs");
  //sacamos doc de la col
  const designsSnapshot = await getDocs(collectionDesignsRef);
  const designsData = designsSnapshot.docs.map((doc) => {
    return {
      ...doc.data(),
      id: doc.id,
    };
  });
  //mandamos la info
  return designsData;
}

//Mandar mi data a firebase, dejo la funcion por si acaso a futuro la necesito

export async function sendInfo() {
  const designs = [
    {
      idInterno: 1,
      photo: '"./assets/Img/FlorAzul.jpg"',
      title: "Blue Flower Sketch",
      text: "Love to sketch",
      style: "Traditional",
      shop1: "https://www.redbubble.com/es/shop/ap/44215676?asc=u",
      shop2: "https://society6.com/product/blue-flower-sketch_print",
      shop3: "https://displate.com//displate/1769006?art=5c9d663484046",
      stock: 1,
      price: 10,
    },
    {
      idInterno: 2,
      photo: '"./assets/Img/CactusSketch.jpg"',
      title: "Cactus Sketch",
      text: "Love to sketch",
      style: "Traditional",
      shop1: "https://www.redbubble.com/es/shop/ap/44713626?asc=u",
      shop2: "https://society6.com/product/cactus-sketch2609163_print",
      shop3: "https://displate.com//displate/1821170?art=5c9d663484046",
      stock: 2,
      price: 20,
    },
    {
      idInterno: 3,
      photo: '"./assets/Img/ChickenNugget.jpg"',
      title: "Chicken Nuguet",
      text: "Weird things comes with food",
      style: "Digital",
      shop1: "https://www.redbubble.com/es/shop/ap/39029341?asc=u",
      shop2: "https://society6.com/product/chicken-nugget2094064_print",
      shop3: "",
      stock: 3,
      price: 30,
    },
    {
      idInterno: 4,
      photo: '"./assets/Img/Chiva1.jpg"',
      title: "Chiva 1",
      text: "Typical Colombian Style",
      style: "Digital",
      shop1: "https://www.redbubble.com/es/shop/ap/37680146?asc=u",
      shop2: "https://society6.com/product/chiva-1_print",
      shop3: "",
      stock: 4,
      price: 10,
    },
    {
      idInterno: 5,
      photo: '"./assets/Img/ChivaPapillon.jpg"',
      title: "Chiva Papillon",
      text: "Typical Colombian Style",
      style: "Digital",
      shop1: "https://www.redbubble.com/es/shop/ap/37791536?asc=u",
      shop2: "https://society6.com/product/chiva-butterfly_print",
      shop3: "",
      stock: 5,
      price: 20,
    },
    {
      idInterno: 6,
      photo: '"./assets/Img/EcoMap.jpg"',
      title: "Echo Map",
      text: "Echoes from the history ares reflected on maps",
      style: "Digital",
      shop1: "https://www.redbubble.com/es/shop/ap/41927627?asc=u",
      shop2: "https://society6.com/product/echo-map-latinoamerica_print",
      shop3: "https://displate.com/displate/1388709?art=5c9d663484046",
      stock: 6,
      price: 30,
    },
    {
      idInterno: 7,
      photo: '"./assets/Img/ElCoco.jpg"',
      title: "El Coco",
      text: "Traditional stories ",
      style: "Digital",
      shop1: "https://www.redbubble.com/es/shop/ap/39471743?asc=u",
      shop2: "",
      shop3: "",
      stock: 7,
      price: 10,
    },
    {
      idInterno: 8,
      photo: '"./assets/Img/Elefante.jpg"',
      title: "Elephant",
      text: "Great animals for great ideas",
      style: "Traditional",
      shop1: "https://www.redbubble.com/es/shop/ap/43470538?asc=u",
      shop2: "https://society6.com/product/elephant2521959_print",
      shop3: "",
      stock: 8,
      price: 20,
    },
    {
      idInterno: 9,
      photo: '"./assets/Img/Fish.jpg"',
      title: "Fish",
      text: "Great animals for great ideas",
      style: "Traditional",
      shop1: "https://www.redbubble.com/es/shop/ap/33278445?asc=u",
      shop2: "https://society6.com/product/fish-0vm_print",
      shop3: "",
      stock: 9,
      price: 30,
    },
    {
      idInterno: 10,
      photo: '"./assets/Img/Flamingo.jpg"',
      title: "Flamingo",
      text: "flamingo love",
      style: "Digital",
      shop1: "https://www.redbubble.com/es/shop/ap/33278103?asc=u",
      shop2: "https://society6.com/product/flamingo-cqw_print",
      shop3: "https://displate.com//displate/1622080?art=5c9d663484046",
      stock: 10,
      price: 10,
    },
    {
      idInterno: 11,
      photo: '"./assets/Img/work-43873587-primary-u-case-iphone.jpg"',
      title: "Yellow flower sketch",
      text: "Love to sketch",
      style: "Traditional",
      shop1: "https://www.redbubble.com/es/shop/ap/43873587?asc=u",
      shop2: "https://society6.com/product/yellow-flower2553552_print",
      shop3: "https://displate.com/displate/1733922?art=5c9d663484046",
      stock: 11,
      price: 20,
    },
    {
      idInterno: 12,
      photo: '"./assets/Img/work-44080791-default-u-coasters.jpg"',
      title: "Purpple flower sketch",
      text: "Love to sketch",
      style: "Traditional",
      shop1: "https://www.redbubble.com/es/shop/ap/44080791?asc=u",
      shop2: "https://society6.com/product/purpple-flower-sketch_print",
      shop3: "https://displate.com/displate/1757905?art=5c9d663484046",
      stock: 12,
      price: 30,
    },
    {
      idInterno: 13,
      photo:
        '"./assets/Img/work-44407738-supplementary-u-case-wallet-iphone.jpg"',
      title: "Pink Flower Sketch",
      text: "Love to sketch",
      style: "Traditional",
      shop1: "https://www.redbubble.com/es/shop/ap/44407738?asc=u",
      shop2: "https://society6.com/product/sketch-flower-pink-2_print",
      shop3: "https://displate.com/displate/1789114?art=5c9d663484046",
      stock: 13,
      price: 10,
    },
    {
      idInterno: 14,
      photo: '"./assets/Img/work-43783422-primary-u-pillow-throw.jpg"',
      title: "Cat",
      text: "Great animals for great ideas",
      style: "Traditional",
      shop1: "https://www.redbubble.com/es/shop/ap/43783422?asc=u",
      shop2: "https://society6.com/product/cat2548588_print",
      shop3: "",
      stock: 14,
      price: 20,
    },
    {
      idInterno: 15,
      photo: '"./assets/Img/work-38170654-primary-u-sticker.jpg"',
      title: "Chocolate Icecream",
      text: "Love Chocolate and Icecream",
      style: "Traditional",
      shop1: "https://www.redbubble.com/es/shop/ap/38170654?asc=u",
      shop2: "https://society6.com/product/ice-cream1995942_print",
      shop3: "",
      stock: 15,
      price: 30,
    },
    {
      idInterno: 16,
      photo: '"./assets/Img/work-38225870-primary-u-pillow-throw.jpg"',
      title: "Vainilla Icecream",
      text: "Love Icecream",
      style: "Traditional",
      shop1: "https://www.redbubble.com/es/shop/ap/38225870",
      shop2: "https://society6.com/product/vainilla-ice-cream_print",
      shop3: "",
      stock: 16,
      price: 10,
    },
    {
      idInterno: 17,
      photo: '"./assets/Img/work-40752226-primary-u-cotton-tote.jpg"',
      title: "Jaguar",
      text: "Typical Colombian Style",
      style: "Digital",
      shop1: "https://www.redbubble.com/es/shop/ap/40752226?asc=u",
      shop2: "https://society6.com/product/jaguar2302812_print",
      shop3: "",
      stock: 17,
      price: 20,
    },
    {
      idInterno: 18,
      photo: '"./assets/Img/work-41996900-primary-u-print-poster.jpg"',
      title: "Latinoamerica resiste",
      text: "Latinoamerica always fighting",
      style: "Digital",
      shop1: "https://www.redbubble.com/es/shop/ap/41996900?asc=u",
      shop2: "",
      shop3: "https://displate.com/displate/1394453?art=5c9d663484046",
      stock: 18,
      price: 30,
    },
    {
      idInterno: 19,
      photo: '"./assets/Img/work-36355711-supplementary-u-print-frame.jpg"',
      title: "Light House",
      text: "There's a light in the worst Storm",
      style: "Digital",
      shop1: "https://www.redbubble.com/es/shop/ap/36355711?asc=u",
      shop2: "https://society6.com/product/splash-lighthouse_print",
      shop3: "",
      stock: 19,
      price: 10,
    },
    {
      idInterno: 20,
      photo: '"./assets/Img/work-39200279-primary-u-case-samsung.jpg"',
      title: "Love Pattern",
      text: "Typical Colombian Style",
      style: "Traditional",
      shop1: "https://www.redbubble.com/es/shop/ap/39200279?asc=u",
      shop2: "https://society6.com/product/pattern-love2109739_print",
      shop3: "",
      stock: 20,
      price: 20,
    },
    {
      idInterno: 21,
      photo: '"./assets/Img/work-38154503-supplementary-u-clock.jpg"',
      title: "Margarita Blue",
      text: "Simple lines Makes great Spaces",
      style: "Digital",
      shop1: "https://www.redbubble.com/es/shop/ap/38154503?asc=u",
      shop2: "https://society6.com/product/daisy-flower1995955_print",
      shop3: "",
      stock: 21,
      price: 30,
    },
    {
      idInterno: 22,
      photo: '"./assets/Img/work-44529824-primary-u-water-bottle.jpg"',
      title: "Margarita Sketch",
      text: "Love to sketch",
      style: "Traditional",
      shop1: "https://www.redbubble.com/es/shop/ap/44529824?asc=u",
      shop2: "https://society6.com/product/margarita-sketch_print",
      shop3: "https://displate.com/displate/1801033?art=5c9d663484046",
      stock: 22,
      price: 10,
    },
    {
      idInterno: 23,
      photo: '"./assets/Img/work-33278258-primary_square-u-bag-tote.jpg"',
      title: "Max",
      text: "Great animals for great ideas",
      style: "Traditional",
      shop1: "https://www.redbubble.com/es/shop/ap/33278258?asc=u",
      shop2: "https://society6.com/product/max-1ci_print",
      shop3: "",
      stock: 23,
      price: 20,
    },
    {
      idInterno: 24,
      photo: '"./assets/Img/work-38647203-supplementary-u-sticker.jpg"',
      title: "Mountain",
      text: "Floating Iselands",
      style: "Digital",
      shop1: "https://www.redbubble.com/es/shop/ap/38647203?asc=u",
      shop2: "https://society6.com/product/floating-earth2060332_print",
      shop3: "",
      stock: 24,
      price: 30,
    },
    {
      idInterno: 25,
      photo: '"./assets/Img/work-44892419-supplementary2-u-block-acrylic.jpg"',
      title: "Orquidea sketch",
      text: "Love to sketch",
      style: "Traditional",
      shop1: "https://www.redbubble.com/es/shop/ap/44892419?asc=u",
      shop2: "https://society6.com/product/orchid-sketch2619670_print",
      shop3: "",
      stock: 25,
      price: 10,
    },
    {
      idInterno: 26,
      photo: '"./assets/Img/work-43187519-primary-u-notebook-hardcover.jpg"',
      title: "Guacamaya",
      text: "Great animals for great ideas",
      style: "Digital",
      shop1: "https://www.redbubble.com/es/shop/ap/43187519?asc=u",
      shop2: "https://society6.com/product/bird2507147_print",
      shop3: "",
      stock: 26,
      price: 20,
    },
    {
      idInterno: 27,
      photo: '"./assets/Img/work-40737896-primary-u-case-ipad.jpg"',
      title: "Golden Muisca Pattern",
      text: "Typical Colombian Style",
      style: "Digital",
      shop1: "https://www.redbubble.com/es/shop/ap/40737896?asc=u",
      shop2: "https://society6.com/product/gold-muisca-pattern_print",
      shop3: "",
      stock: 27,
      price: 30,
    },
    {
      idInterno: 28,
      photo: '"./assets/Img/work-40099037-primary-u-pillow-floor.jpg"',
      title: "Black Muisca Pattern",
      text: "Typical Colombian Style",
      style: "Digital",
      shop1: "https://www.redbubble.com/es/shop/ap/40099037?asc=u",
      shop2: "https://society6.com/product/muisca-pattern_print",
      shop3: "",
      stock: 28,
      price: 10,
    },
    {
      idInterno: 29,
      photo: '"./assets/Img/work-36431178-primary-u-print-metal.jpg"',
      title: "Photo Flower 1",
      text: "Flowers are Great Models",
      style: "Photography",
      shop1: "https://www.redbubble.com/es/shop/ap/36431178?asc=u",
      shop2: "https://society6.com/product/flower-3896016_print",
      shop3: "",
      stock: 29,
      price: 20,
    },
    {
      idInterno: 30,
      photo: '"./assets/Img/work-41498001-supplementary-u-print-frame.jpg"',
      title: "Pills Cowboy",
      text: "Living with depression is an adventure of pills",
      style: "Digital",
      shop1: "https://www.redbubble.com/es/shop/ap/41498001?asc=u",
      shop2: "https://society6.com/product/pills-cowboy_print",
      shop3: "https://displate.com/displate/1356330?art=5c9d663484046",
      stock: 30,
      price: 30,
    },
    {
      idInterno: 31,
      photo: '"./assets/Img/work-44252414-primary-u-pillow-throw.jpg"',
      title: "Pink Flower Sketch",
      text: "Love to sketch",
      style: "Traditional",
      shop1: "https://www.redbubble.com/es/shop/ap/44252414?asc=u",
      shop2: "https://society6.com/product/pink-sketch-flower_print",
      shop3: "https://displate.com/displate/1773317?art=5c9d663484046",
      stock: 31,
      price: 10,
    },
    {
      idInterno: 32,
      photo: '"./assets/Img/work-33297362-primary_square-u-block-acrylic.jpg"',
      title: "Octopus",
      text: "Great animals for great ideas",
      style: "Traditional",
      shop1: "https://www.redbubble.com/es/shop/ap/33297362?asc=u",
      shop2: "https://society6.com/product/ninetopus_print",
      shop3: "",
      stock: 32,
      price: 20,
    },
    {
      idInterno: 33,
      photo: '"./assets/Img/work-36201257-primary-u-bag-tote.jpg"',
      title: "Mice",
      text: "Great animals for great ideas",
      style: "Traditional",
      shop1: "https://www.redbubble.com/es/shop/ap/36201257?asc=u",
      shop2: "https://society6.com/product/mouse-ino_print",
      shop3: "",
      stock: 33,
      price: 30,
    },
    {
      idInterno: 34,
      photo: '"./assets/Img/work-43974602-primary-u-pillow-floor.jpg"',
      title: "Rose Sketch",
      text: "Love to sketch",
      style: "Traditional",
      shop1: "https://www.redbubble.com/es/shop/ap/43974602?asc=u",
      shop2: "https://society6.com/product/rose-sketch2558924_print",
      shop3: "https://displate.com/displate/1740850?art=5c9d663484046",
      stock: 34,
      price: 10,
    },
    {
      idInterno: 35,
      photo: '"./assets/Img/work-44834524-default-u-bag-studiopouch.jpg"',
      title: "Rose Pattern",
      text: "Love Flowers",
      style: "Traditional",
      shop1: "https://www.redbubble.com/es/shop/ap/44834524?asc=u",
      shop2: "",
      shop3: "",
      stock: 35,
      price: 20,
    },
    {
      idInterno: 36,
      photo: '"./assets/Img/Flamingo.jpg"',
      title: "Chiva Texture",
      text: "Typical Colombian Style",
      style: "Digital",
      shop1: "https://www.redbubble.com/es/shop/ap/38018380?asc=u",
      shop2: "https://society6.com/product/chiva-pattern_print",
      shop3: "",
      stock: 36,
      price: 30,
    },
    {
      idInterno: 37,
      photo: '"./assets/Img/Flamingo.jpg"',
      title: "Vainilla y Chocolate Pattern",
      text: "Love Icecream",
      style: "Traditional",
      shop1: "https://www.redbubble.com/es/shop/ap/41384860?asc=u",
      shop2: "https://society6.com/product/icecream-pattern2329844_print",
      shop3: "",
      stock: 37,
      price: 10,
    },
    {
      idInterno: 38,
      photo: '"./assets/Img/Flamingo.jpg"',
      title: "Vainilla y Chocolate",
      text: "Love Icecream",
      style: "Traditional",
      shop1: "https://www.redbubble.com/es/shop/ap/38226289?asc=u",
      shop2: "https://society6.com/product/vainilla-or-chocolate_print",
      shop3: "",
      stock: 38,
      price: 20,
    },
    {
      idInterno: 39,
      photo: '"./assets/Img/Flamingo.jpg"',
      title: "Vector Fox",
      text: "Great animals for great ideas",
      style: "Digital",
      shop1: "https://www.redbubble.com/es/shop/ap/39218996?asc=u",
      shop2: "https://society6.com/product/fox353468_print",
      shop3: "",
      stock: 39,
      price: 30,
    },
    {
      idInterno: 40,
      photo: '"./assets/Img/Flamingo.jpg"',
      title: "Unicornio",
      text: "Great animals for great ideas",
      style: "Digital",
      shop1: "https://www.redbubble.com/es/shop/ap/57521334?asc=u",
      shop2: "https://society6.com/product/unicorn-with-hoodie_print",
      shop3: "",
      stock: 40,
      price: 10,
    },
    {
      idInterno: 41,
      photo: '"./assets/Img/Flamingo.jpg"',
      title: "Transformation",
      text: "Learn to transform over time for good",
      style: "Traditional",
      shop1: "https://www.redbubble.com/es/shop/ap/54892390?asc=u",
      shop2: "https://society6.com/product/transformation3353190_print",
      shop3: "https://displate.com/displate/3471895",
      stock: 41,
      price: 20,
    },
    {
      idInterno: 42,
      photo: '"./assets/Img/Flamingo.jpg"',
      title: "Taco Time",
      text: "Always is a good time for a taco",
      style: "Digital",
      shop1: "https://www.redbubble.com/es/shop/ap/48772536?asc=u",
      shop2: "https://society6.com/product/taco-time2905170_print",
      shop3: "https://displate.com/displate/2549782?art=5c9d663484046",
      stock: 42,
      price: 30,
    },
    {
      idInterno: 43,
      photo: '"./assets/Img/Flamingo.jpg"',
      title: "Pattern Avocado",
      text: "Always is a good time for a Avocado",
      style: "Digital",
      shop1: "https://www.redbubble.com/es/shop/ap/49048340?asc=u",
      shop2: "",
      shop3: "",
      stock: 43,
      price: 10,
    },
    {
      idInterno: 44,
      photo: '"./assets/Img/Flamingo.jpg"',
      title: "Make it real Dino",
      text: "Work for your dreams",
      style: "Digital",
      shop1: "https://www.redbubble.com/es/shop/ap/58154695?asc=u",
      shop2: "https://society6.com/product/make-it-real3386947_print",
      shop3: "",
      stock: 44,
      price: 20,
    },
    {
      idInterno: 45,
      photo: '"./assets/Img/Flamingo.jpg"',
      title: "Chili Pepper pattern",
      text: "Spicy time",
      style: "Digital",
      shop1: "https://www.redbubble.com/es/shop/ap/49192557?asc=u",
      shop2: "",
      shop3: "",
      stock: 45,
      price: 30,
    },
    {
      idInterno: 46,
      photo: '"./assets/Img/Flamingo.jpg"',
      title: "Octopus Mind",
      text: "Multitasking to other level",
      style: "Digital",
      shop1: "https://www.redbubble.com/es/shop/ap/56400235?asc=u",
      shop2: "https://society6.com/product/octopus-mind_print",
      shop3: "",
      stock: 46,
      price: 10,
    },
    {
      idInterno: 47,
      photo: '"./assets/Img/Flamingo.jpg"',
      title: "Notice the message",
      text: "Nature give us many messages",
      style: "Traditional",
      shop1: "https://www.redbubble.com/es/shop/ap/55573797?asc=u",
      shop2: "https://society6.com/product/notice-the-message3348244_print",
      shop3: "https://displate.com//displate/3601891?art=5c9d663484046",
      stock: 47,
      price: 20,
    },
    {
      idInterno: 48,
      photo: '"./assets/Img/Flamingo.jpg"',
      title: "Make It Real",
      text: "Work for your dreams",
      style: "Digital",
      shop1: "https://www.redbubble.com/es/shop/ap/58789258?asc=u",
      shop2: "",
      shop3: "",
      stock: 48,
      price: 30,
    },
    {
      idInterno: 49,
      photo: '"./assets/Img/Flamingo.jpg"',
      title: "Screaming egg",
      text: "Weird things comes with food",
      style: "Digital",
      shop1: "https://www.redbubble.com/es/shop/ap/57269998?asc=u",
      shop2: "https://society6.com/product/screaming-egg_print",
      shop3: "",
      stock: 49,
      price: 10,
    },
    {
      idInterno: 50,
      photo: '"./assets/Img/Flamingo.jpg"',
      title: "Fly Away",
      text: "Let your dreams fly",
      style: "Traditional",
      shop1: "https://www.redbubble.com/es/shop/ap/53228277?asc=u",
      shop2: "https://society6.com/product/fly-away3144120_print",
      shop3: "https://displate.com/displate/3311641?art=5c9d663484046",
      stock: 50,
      price: 20,
    },
    {
      idInterno: 51,
      photo: '"./assets/Img/Flamingo.jpg"',
      title: "Pills Explosion",
      text: "Living with depression is an adventure of pills",
      style: "Digital",
      shop1: "https://www.redbubble.com/es/shop/ap/48271682?asc=u",
      shop2: "",
      shop3: "https://displate.com/displate/2461626?art=5c9d663484046",
      stock: 51,
      price: 30,
    },
    {
      idInterno: 52,
      photo: '"./assets/Img/Flamingo.jpg"',
      title: "Bird Sketch",
      text: "Love to sketch",
      style: "Traditional",
      shop1: "https://www.redbubble.com/es/shop/ap/45980421?asc=u",
      shop2: "https://society6.com/product/bird-sketch2700902_print",
      shop3: "https://displate.com/displate/2065495?art=5c9d663484046",
      stock: 52,
      price: 10,
    },
    {
      idInterno: 53,
      photo: '"./assets/Img/Flamingo.jpg"',
      title: "Boceto Colibri",
      text: "Love to sketch",
      style: "Traditional",
      shop1: "https://www.redbubble.com/es/shop/ap/46318282?asc=u",
      shop2: "https://society6.com/product/hummingbird-sketch2729513_print",
      shop3: "https://displate.com/displate/2130336?art=5c9d663484046",
      stock: 53,
      price: 20,
    },
    {
      idInterno: 54,
      photo: '"./assets/Img/Flamingo.jpg"',
      title: "Cool Cactus",
      text: "Word Play",
      style: "Digital",
      shop1: "https://www.redbubble.com/es/shop/ap/45527464?asc=u",
      shop2: "",
      shop3: "",
      stock: 54,
      price: 30,
    },
    {
      idInterno: 55,
      photo: '"./assets/Img/Flamingo.jpg"',
      title: "Doodle Box Color",
      text: "Ideas Everywere",
      style: "Digital",
      shop1: "https://www.redbubble.com/es/shop/ap/46103998?asc=u",
      shop2: "https://society6.com/product/doodle-box-color_print",
      shop3: "https://displate.com/displate/2090444?art=5c9d663484046",
      stock: 55,
      price: 10,
    },
    {
      idInterno: 56,
      photo: '"./assets/Img/Flamingo.jpg"',
      title: "Doodle Box Duotone",
      text: "Ideas Everywere",
      style: "Digital",
      shop1: "https://www.redbubble.com/es/shop/ap/46427176?asc=u",
      shop2: "https://society6.com/product/doodle-box-lines_print",
      shop3: "",
      stock: 56,
      price: 20,
    },
    {
      idInterno: 57,
      photo: '"./assets/Img/Flamingo.jpg"',
      title: "Doodle Box Lines",
      text: "Ideas Everywere",
      style: "Digital",
      shop1: "https://www.redbubble.com/es/shop/ap/46129433?asc=u",
      shop2: "",
      shop3: "https://displate.com/displate/2111229?art=5c9d663484046",
      stock: 57,
      price: 30,
    },
  ];
  const designsRef = collection(DB, "designs");
  //se hace for of y no foreach (diferencia en logica interna entre metodos)
  for (let i of designs){
    
    let docOrder = await addDoc(designsRef, i);
    console.log("documento creado id", docOrder.id);
  }
}
